sudo: required
os: linux
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - stable
braches:
  only:
    - master
before_script:
  - npm install -g ionic cordova
script:
  - npm install
  - ionic platform add android@latest
  - cp signing/debug-signing.properties platforms/android/
  - ionic cordova build android
  - npm test
