sudo: enabled
os: linux
dist: trusty
group: stable
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - node
braches:
  only:
    - master
before_install:
  - npm i -g npm@5.6.0
cache:
  directories:
    - node_modules
before_script:
  - npm install
  - ionic cordova platform add android@latest
  - cp signing/debug-signing.properties platforms/android/
  - ionic cordova build android
script:
  - npm test
