sudo: enabled
os: linux
dist: trusty
group: stable
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - stable
braches:
  only:
    - master
before_install:
  - npm install
  - ionic cordova platform add android@latest
  - cp signing/debug-signing.properties platforms/android/
  - ionic cordova build android
after_success:
  - npm test
